##Import the Libraries

In [57]:
import numpy as np
import pandas as pd

##Load the Dataset

In [58]:
data = pd.read_excel('Dataset for Data Analytics.xlsx')
data.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

##Information About the Dataset

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

##Handling the Null Values

In [60]:
''' Null values of coupon code defines that
    there is no coupon code applied on that order by the customer
    so we handle it by filling the null values with NA '''

data['CouponCode'] = data['CouponCode'].fillna('NA')
print(data.isnull().sum())

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

#Check For Duplicates

In [61]:
''' No duplicates are there in dataset
    So no need to handle them'''
data.duplicated().sum()

np.int64(0)

##Check For White Spaces

In [62]:
#Select all the columns with categorical values
string_cols = data.select_dtypes(include='object')

#Removing the whitespaces from starting, ending, and between words
data[string_cols.columns] = string_cols.apply(lambda col: col.str.replace(r'\s+', '', regex=True).str.strip())

##Check For Date Format

In [63]:
#To Check all the dates are in proper format or not
date_mask = pd.to_datetime(data['Date'], format='%Y-%m-%d', errors = 'coerce').notna()
print(data[~date_mask])
#All the dates are in proper format
data.head()

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928MainSt,DebitCard,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823MainSt,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512MainSt,CreditCard,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275MainSt,DebitCard,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668MainSt,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

##Check For Numeric Precision (2 Decimals)

In [64]:
numeric_cols = ['UnitPrice', 'TotalPrice']

NP_mask = data[numeric_cols].apply(
    lambda col: ((col * 100).round(6) % 1 == 0)
)

print(data.loc[~NP_mask.all(axis=1), numeric_cols])
#No entry in both the columns having more than 2 precision

Empty DataFrame
Columns: [UnitPrice, TotalPrice]
Index: []

##Final Check:
##1. Error Rate on OrderID
##2. Error Rate on Date Formats

In [67]:
#Calculating Error Rate for OrderID

duplicate_count = data['OrderID'].duplicated().sum()
total_rows = len(data)
error_rate_OID = (duplicate_count / total_rows) * 100

#Calculating Error Rate on Date Formats

invalid_dates = (~date_mask).sum()
error_rate_DF = (invalid_dates / total_rows) * 100
print(f'{error_rate_OID: .2f}% Error Rate on Unique Identifiers')
print(f'{error_rate_DF: .2f}% Error Rate on Date Formats')

 0.00% Error Rate on Unique Identifiers
 0.00% Error Rate on Date Formats